<template>
  <div>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  <p>这是switch文档</p>
  </div>
</template>
<script  lang="ts">
export default {

}
</script>
<style>
</style>
